// generated by gen-nodes from `v2c-chunk.t'.  Do not edit.

#include "v2c-chunk.h"

tree_generic<v2c_generic_0_mtype> v2c_generic_0;

void emit_def (tree_base_node *__node__)
{
  v2c_generic_0_mtype __method__ = 
    v2c_generic_0.find (__node__->kind ());
  (*__method__) (__node__);
}

tree_generic<v2c_generic_1_mtype> v2c_generic_1;

void emit_decl (tree_base_node *__node__, int l)
{
  v2c_generic_1_mtype __method__ = 
    v2c_generic_1.find (__node__->kind ());
  (*__method__) (__node__, l);
}

tree_generic<v2c_generic_2_mtype> v2c_generic_2;

void emit_stat (tree_base_node *__node__, int l)
{
  v2c_generic_2_mtype __method__ = 
    v2c_generic_2.find (__node__->kind ());
  (*__method__) (__node__, l);
}

tree_generic<v2c_generic_3_mtype> v2c_generic_3;

void emit_expr (tree_base_node *__node__)
{
  v2c_generic_3_mtype __method__ = 
    v2c_generic_3.find (__node__->kind ());
  (*__method__) (__node__);
}

tree_generic<v2c_generic_4_mtype> v2c_generic_4;

void emit_conc_stat (tree_base_node *__node__, int l)
{
  v2c_generic_4_mtype __method__ = 
    v2c_generic_4.find (__node__->kind ());
  (*__method__) (__node__, l);
}

tree_generic<v2c_generic_5_mtype> v2c_generic_5;

void emit_start_of_context (tree_base_node *__node__, int l)
{
  v2c_generic_5_mtype __method__ = 
    v2c_generic_5.find (__node__->kind ());
  (*__method__) (__node__, l);
}

tree_generic<v2c_generic_6_mtype> v2c_generic_6;

void emit_end_of_context (tree_base_node *__node__, int l)
{
  v2c_generic_6_mtype __method__ = 
    v2c_generic_6.find (__node__->kind ());
  (*__method__) (__node__, l);
}

static v2c_generic_0_mtype mtab_0_fire[] = {
  0, // IIR_Root
  0, // IIR_SequentialStatement
  0, // IIR_NullStatement
  0, // IIR_ReturnStatement
  0, // IIR_LoopControlStatement
  0, // IIR_ExitStatement
  0, // IIR_NextStatement
  0, // IIR_LoopStatement
  0, // IIR_WhileLoopStatement
  0, // IIR_ForLoopStatement
  0, // IIR_CaseStatement
  0, // IIR_IfStatement
  0, // IIR_ProcedureCallStatement
  0, // IIR_VariableAssignmentStatement
  0, // IIR_SignalAssignmentStatement
  0, // IIR_ReportStatement
  0, // IIR_AssertionStatement
  0, // IIR_WaitStatement
  0, // IIR_Expression
  0, // IIR_ValueAttr
  0, // IIR_AttrTypeValue
  0, // IIR_Attr_LENGTH
  0, // IIR_Attr_ASCENDING
  0, // IIR_Attr_HIGH
  0, // IIR_Attr_LOW
  0, // IIR_Attr_RIGHT
  0, // IIR_Attr_LEFT
  0, // IIR_FunctionAttr
  0, // IIR_AttrArrayFunc
  0, // IIR_Attr_ArrayLENGTH
  0, // IIR_Attr_ArrayASCENDING
  0, // IIR_Attr_ArrayLOW
  0, // IIR_Attr_ArrayHIGH
  0, // IIR_Attr_ArrayRIGHT
  0, // IIR_Attr_ArrayLEFT
  0, // IIR_AttrTypeFunc
  0, // IIR_Attr_RIGHTOF
  0, // IIR_Attr_LEFTOF
  0, // IIR_Attr_PRED
  0, // IIR_Attr_SUCC
  0, // IIR_Attr_VAL
  0, // IIR_Attr_POS
  0, // IIR_Attr_VALUE
  0, // IIR_Attr_IMAGE
  0, // IIR_AttrSigFunc
  0, // IIR_Attr_DRIVING_VALUE
  0, // IIR_Attr_DRIVING
  0, // IIR_Attr_LAST_VALUE
  0, // IIR_Attr_LAST_ACTIVE
  0, // IIR_Attr_LAST_EVENT
  0, // IIR_Attr_ACTIVE
  0, // IIR_Attr_EVENT
  0, // IIR_ObjectReference
  0, // IIR_SignalAttr
  0, // IIR_Attr_TRANSACTION
  0, // IIR_Attr_QUIET
  0, // IIR_Attr_STABLE
  0, // IIR_Attr_DELAYED
  0, // IIR_GenericArrayReference
  0, // IIR_SliceReference
  0, // IIR_ArrayReference
  0, // IIR_RecordReference
  0, // IIR_AccessReference
  0, // IIR_SimpleReference
  0, // IIR_OpenExpression
  0, // IIR_Allocator
  0, // IIR_TypeConversion
  0, // IIR_QualifiedExpression
  0, // IIR_FunctionCall
  0, // IIR_Aggregate
  0, // IIR_ArrayAggregate
  0, // IIR_ArtificialArrayAggregate
  0, // IIR_RecordAggregate
  0, // IIR_ArtificialRecordAggregate
  0, // IIR_NullExpression
  0, // IIR_EnumLiteralReference
  0, // IIR_ArrayLiteralExpression
  0, // IIR_AbstractLiteralExpression
  0, // IIR_PhysicalLiteral
  0, // IIR_Declaration
  0, // IIR_UseClause
  0, // IIR_LibraryClause
  0, // IIR_Label
  0, // IIR_DisconnectSpecification
  0, // IIR_PhysicalUnit
  0, // IIR_LibraryDeclaration
  0, // IIR_AttributeDeclaration
  0, // IIR_ObjectDeclaration
  0, // IIR_InterfaceDeclaration
  0, // IIR_FileInterfaceDeclaration
  0, // IIR_SignalInterfaceDeclaration
  0, // IIR_VariableInterfaceDeclaration
  0, // IIR_ConstantInterfaceDeclaration
  0, // IIR_FileDeclaration
  0, // IIR_SignalDeclaration
  0, // IIR_VariableDeclaration
  0, // IIR_SharedVariableDeclaration
  0, // IIR_ConstantDeclaration
  0, // IIR_TypeDeclaration
  0, // IIR_SubtypeDeclaration
  0, // IIR_ElementDeclaration
  0, // IIR_EnumerationLiteral
  0, // IIR_DeclarativeRegion
  0, // IIR_ConcurrentStatement
  0, // IIR_ConcurrentGenerateStatement
  0, // IIR_ConcurrentGenerateIfStatement
  0, // IIR_ConcurrentGenerateForStatement
  0, // IIR_ComponentInstantiationStatement
  0, // IIR_ProcessStatement
  0, // IIR_SensitizedProcessStatement
  0, // IIR_ImplicitProcessStatement
  0, // IIR_BlockStatement
  0, // IIR_ConfigurationItem
  0, // IIR_ComponentConfiguration
  0, // IIR_BlockConfiguration
  0, // IIR_ArchitectureRef
  0, // IIR_LibraryUnit
  0, // IIR_ConfigurationDeclaration
  0, // IIR_PackageBodyDeclaration
  0, // IIR_PackageDeclaration
  0, // IIR_ArchitectureDeclaration
  0, // IIR_EntityDeclaration
  0, // IIR_ComponentDeclaration
  0, // IIR_SubprogramDeclaration
  0, // IIR_FunctionDeclaration
  0, // IIR_PredefinedFunctionDeclaration
  0, // IIR_ProcedureDeclaration
  0, // IIR_PredefinedProcedureDeclaration
  0, // IIR_LoopDeclarativeRegion
  (v2c_generic_0_mtype) ((void (*)(pIIR_Type))&m_emit_def),  // IIR_Type
  (v2c_generic_0_mtype) ((void (*)(pIIR_FileType))&m_emit_def),  // IIR_FileType
  (v2c_generic_0_mtype) ((void (*)(pIIR_Type))&m_emit_def),  // IIR_AccessType
  (v2c_generic_0_mtype) ((void (*)(pIIR_Type))&m_emit_def),  // IIR_CompositeType
  (v2c_generic_0_mtype) ((void (*)(pIIR_ArrayType))&m_emit_def),  // IIR_ArrayType
  (v2c_generic_0_mtype) ((void (*)(pIIR_RecordType))&m_emit_def),  // IIR_RecordType
  (v2c_generic_0_mtype) ((void (*)(pIIR_Type))&m_emit_def),  // IIR_ScalarType
  (v2c_generic_0_mtype) ((void (*)(pIIR_PhysicalType))&m_emit_def),  // IIR_PhysicalType
  (v2c_generic_0_mtype) ((void (*)(pIIR_FloatingType))&m_emit_def),  // IIR_FloatingType
  (v2c_generic_0_mtype) ((void (*)(pIIR_IntegerType))&m_emit_def),  // IIR_IntegerType
  (v2c_generic_0_mtype) ((void (*)(pIIR_EnumerationType))&m_emit_def),  // IIR_EnumerationType
  (v2c_generic_0_mtype) ((void (*)(pIIR_Subtype))&m_emit_def),  // IIR_Subtype
  (v2c_generic_0_mtype) ((void (*)(pIIR_Subtype))&m_emit_def),  // IIR_ArraySubtype
  (v2c_generic_0_mtype) ((void (*)(pIIR_Subtype))&m_emit_def),  // IIR_RecordSubtype
  (v2c_generic_0_mtype) ((void (*)(pIIR_Subtype))&m_emit_def),  // IIR_ScalarSubtype
  0, // IIR_Range
  0, // IIR_ArrayRange
  0, // IIR_Attr_ArrayREVERSE_RANGE
  0, // IIR_Attr_ArrayRANGE
  0, // IIR_ExplicitRange
  0, // IIR_List
  0, // IIR_IdentifierList
  0, // IIR_ConfigurationSpecificationList
  0, // IIR_ComponentInstantiationList
  0, // IIR_ElementAssociationList
  0, // IIR_IndexedAssociationList
  0, // IIR_ExpressionList
  0, // IIR_TypeList
  0, // IIR_WaveformList
  0, // IIR_UnitList
  0, // IIR_SequentialStatementList
  0, // IIR_LibraryUnitList
  0, // IIR_InterfaceList
  0, // IIR_EnumerationLiteralList
  0, // IIR_EntityClassEntryList
  0, // IIR_ElementDeclarationList
  0, // IIR_DeclarationList
  0, // IIR_ConfigurationItemList
  0, // IIR_ConcurrentStatementList
  0, // IIR_ChoiceList
  0, // IIR_CaseStatementAlternativeList
  0, // IIR_AttributeValueList
  0, // IIR_AssociationList
  0, // IIR_Tuple
  0, // IIR_ConfigurationSpecification
  0, // IIR_BindingIndication
  0, // IIR_AttributeValue
  0, // IIR_IndexedAssociation
  0, // IIR_OthersIndexedAssociation
  0, // IIR_RangeIndexedAssociation
  0, // IIR_SliceIndexedAssociation
  0, // IIR_SingleIndexedAssociation
  0, // IIR_ElementAssociation
  0, // IIR_WaveformElement
  0, // IIR_EntityClassEntry
  0, // IIR_Choice
  0, // IIR_ChoiceByOthers
  0, // IIR_ChoiceByRange
  0, // IIR_ChoiceByExpression
  0, // IIR_CaseStatementAlternative
  0, // IIR_AssociationElement
  0, // IIR_AssociationElementOpen
  0, // IIR_AssociationElementByExpression
  0, // IIR_Literal
  0, // IIR_AbstractLiteral
  0, // IIR_FloatingPointLiteral
  0, // IIR_IntegerLiteral
  0, // IIR_TextLiteral
  0, // IIR_StringLiteral
  0, // IIR_CharacterLiteral
  0, // IIR_Identifier
  0, // IIR_Dummy
  0, // IIR_Signature
  0, // IIR_PosInfo
  0, // IIR_PosInfo_Sheet
  0, // IIR_PosInfo_TextFile
};
static tree_chunk_tab ctab_0[1] = {
  { &fire_chunk_info, 205, mtab_0_fire },
};


static v2c_generic_1_mtype mtab_1_fire[] = {
  0, // IIR_Root
  0, // IIR_SequentialStatement
  0, // IIR_NullStatement
  0, // IIR_ReturnStatement
  0, // IIR_LoopControlStatement
  0, // IIR_ExitStatement
  0, // IIR_NextStatement
  0, // IIR_LoopStatement
  0, // IIR_WhileLoopStatement
  0, // IIR_ForLoopStatement
  0, // IIR_CaseStatement
  0, // IIR_IfStatement
  0, // IIR_ProcedureCallStatement
  0, // IIR_VariableAssignmentStatement
  0, // IIR_SignalAssignmentStatement
  0, // IIR_ReportStatement
  0, // IIR_AssertionStatement
  0, // IIR_WaitStatement
  0, // IIR_Expression
  0, // IIR_ValueAttr
  0, // IIR_AttrTypeValue
  0, // IIR_Attr_LENGTH
  0, // IIR_Attr_ASCENDING
  0, // IIR_Attr_HIGH
  0, // IIR_Attr_LOW
  0, // IIR_Attr_RIGHT
  0, // IIR_Attr_LEFT
  0, // IIR_FunctionAttr
  0, // IIR_AttrArrayFunc
  0, // IIR_Attr_ArrayLENGTH
  0, // IIR_Attr_ArrayASCENDING
  0, // IIR_Attr_ArrayLOW
  0, // IIR_Attr_ArrayHIGH
  0, // IIR_Attr_ArrayRIGHT
  0, // IIR_Attr_ArrayLEFT
  0, // IIR_AttrTypeFunc
  0, // IIR_Attr_RIGHTOF
  0, // IIR_Attr_LEFTOF
  0, // IIR_Attr_PRED
  0, // IIR_Attr_SUCC
  0, // IIR_Attr_VAL
  0, // IIR_Attr_POS
  0, // IIR_Attr_VALUE
  0, // IIR_Attr_IMAGE
  0, // IIR_AttrSigFunc
  0, // IIR_Attr_DRIVING_VALUE
  0, // IIR_Attr_DRIVING
  0, // IIR_Attr_LAST_VALUE
  0, // IIR_Attr_LAST_ACTIVE
  0, // IIR_Attr_LAST_EVENT
  0, // IIR_Attr_ACTIVE
  0, // IIR_Attr_EVENT
  0, // IIR_ObjectReference
  0, // IIR_SignalAttr
  0, // IIR_Attr_TRANSACTION
  0, // IIR_Attr_QUIET
  0, // IIR_Attr_STABLE
  0, // IIR_Attr_DELAYED
  0, // IIR_GenericArrayReference
  0, // IIR_SliceReference
  0, // IIR_ArrayReference
  0, // IIR_RecordReference
  0, // IIR_AccessReference
  0, // IIR_SimpleReference
  0, // IIR_OpenExpression
  0, // IIR_Allocator
  0, // IIR_TypeConversion
  0, // IIR_QualifiedExpression
  0, // IIR_FunctionCall
  0, // IIR_Aggregate
  0, // IIR_ArrayAggregate
  0, // IIR_ArtificialArrayAggregate
  0, // IIR_RecordAggregate
  0, // IIR_ArtificialRecordAggregate
  0, // IIR_NullExpression
  0, // IIR_EnumLiteralReference
  0, // IIR_ArrayLiteralExpression
  0, // IIR_AbstractLiteralExpression
  0, // IIR_PhysicalLiteral
  (v2c_generic_1_mtype) ((void (*)(pIIR_Declaration, int l))&m_emit_decl),  // IIR_Declaration
  (v2c_generic_1_mtype) ((void (*)(pIIR_Declaration, int l))&m_emit_decl),  // IIR_UseClause
  (v2c_generic_1_mtype) ((void (*)(pIIR_Declaration, int l))&m_emit_decl),  // IIR_LibraryClause
  (v2c_generic_1_mtype) ((void (*)(pIIR_Declaration, int l))&m_emit_decl),  // IIR_Label
  (v2c_generic_1_mtype) ((void (*)(pIIR_Declaration, int l))&m_emit_decl),  // IIR_DisconnectSpecification
  (v2c_generic_1_mtype) ((void (*)(pIIR_Declaration, int l))&m_emit_decl),  // IIR_PhysicalUnit
  (v2c_generic_1_mtype) ((void (*)(pIIR_Declaration, int l))&m_emit_decl),  // IIR_LibraryDeclaration
  (v2c_generic_1_mtype) ((void (*)(pIIR_Declaration, int l))&m_emit_decl),  // IIR_AttributeDeclaration
  (v2c_generic_1_mtype) ((void (*)(pIIR_Declaration, int l))&m_emit_decl),  // IIR_ObjectDeclaration
  (v2c_generic_1_mtype) ((void (*)(pIIR_Declaration, int l))&m_emit_decl),  // IIR_InterfaceDeclaration
  (v2c_generic_1_mtype) ((void (*)(pIIR_Declaration, int l))&m_emit_decl),  // IIR_FileInterfaceDeclaration
  (v2c_generic_1_mtype) ((void (*)(pIIR_Declaration, int l))&m_emit_decl),  // IIR_SignalInterfaceDeclaration
  (v2c_generic_1_mtype) ((void (*)(pIIR_Declaration, int l))&m_emit_decl),  // IIR_VariableInterfaceDeclaration
  (v2c_generic_1_mtype) ((void (*)(pIIR_Declaration, int l))&m_emit_decl),  // IIR_ConstantInterfaceDeclaration
  (v2c_generic_1_mtype) ((void (*)(pIIR_FileDeclaration, int l))&m_emit_decl),  // IIR_FileDeclaration
  (v2c_generic_1_mtype) ((void (*)(pIIR_SignalDeclaration, int l))&m_emit_decl),  // IIR_SignalDeclaration
  (v2c_generic_1_mtype) ((void (*)(pIIR_VariableDeclaration, int l))&m_emit_decl),  // IIR_VariableDeclaration
  (v2c_generic_1_mtype) ((void (*)(pIIR_VariableDeclaration, int l))&m_emit_decl),  // IIR_SharedVariableDeclaration
  (v2c_generic_1_mtype) ((void (*)(pIIR_ConstantDeclaration, int l))&m_emit_decl),  // IIR_ConstantDeclaration
  (v2c_generic_1_mtype) ((void (*)(pIIR_TypeDeclaration, int l))&m_emit_decl),  // IIR_TypeDeclaration
  (v2c_generic_1_mtype) ((void (*)(pIIR_TypeDeclaration, int l))&m_emit_decl),  // IIR_SubtypeDeclaration
  (v2c_generic_1_mtype) ((void (*)(pIIR_Declaration, int l))&m_emit_decl),  // IIR_ElementDeclaration
  (v2c_generic_1_mtype) ((void (*)(pIIR_Declaration, int l))&m_emit_decl),  // IIR_EnumerationLiteral
  (v2c_generic_1_mtype) ((void (*)(pIIR_Declaration, int l))&m_emit_decl),  // IIR_DeclarativeRegion
  (v2c_generic_1_mtype) ((void (*)(pIIR_Declaration, int l))&m_emit_decl),  // IIR_ConcurrentStatement
  (v2c_generic_1_mtype) ((void (*)(pIIR_Declaration, int l))&m_emit_decl),  // IIR_ConcurrentGenerateStatement
  (v2c_generic_1_mtype) ((void (*)(pIIR_Declaration, int l))&m_emit_decl),  // IIR_ConcurrentGenerateIfStatement
  (v2c_generic_1_mtype) ((void (*)(pIIR_Declaration, int l))&m_emit_decl),  // IIR_ConcurrentGenerateForStatement
  (v2c_generic_1_mtype) ((void (*)(pIIR_Declaration, int l))&m_emit_decl),  // IIR_ComponentInstantiationStatement
  (v2c_generic_1_mtype) ((void (*)(pIIR_Declaration, int l))&m_emit_decl),  // IIR_ProcessStatement
  (v2c_generic_1_mtype) ((void (*)(pIIR_Declaration, int l))&m_emit_decl),  // IIR_SensitizedProcessStatement
  (v2c_generic_1_mtype) ((void (*)(pIIR_Declaration, int l))&m_emit_decl),  // IIR_ImplicitProcessStatement
  (v2c_generic_1_mtype) ((void (*)(pIIR_Declaration, int l))&m_emit_decl),  // IIR_BlockStatement
  (v2c_generic_1_mtype) ((void (*)(pIIR_Declaration, int l))&m_emit_decl),  // IIR_ConfigurationItem
  (v2c_generic_1_mtype) ((void (*)(pIIR_Declaration, int l))&m_emit_decl),  // IIR_ComponentConfiguration
  (v2c_generic_1_mtype) ((void (*)(pIIR_Declaration, int l))&m_emit_decl),  // IIR_BlockConfiguration
  (v2c_generic_1_mtype) ((void (*)(pIIR_Declaration, int l))&m_emit_decl),  // IIR_ArchitectureRef
  (v2c_generic_1_mtype) ((void (*)(pIIR_Declaration, int l))&m_emit_decl),  // IIR_LibraryUnit
  (v2c_generic_1_mtype) ((void (*)(pIIR_ConfigurationDeclaration, int l))&m_emit_decl),  // IIR_ConfigurationDeclaration
  (v2c_generic_1_mtype) ((void (*)(pIIR_PackageBodyDeclaration, int l))&m_emit_decl),  // IIR_PackageBodyDeclaration
  (v2c_generic_1_mtype) ((void (*)(pIIR_PackageDeclaration, int l))&m_emit_decl),  // IIR_PackageDeclaration
  (v2c_generic_1_mtype) ((void (*)(pIIR_ArchitectureDeclaration, int l))&m_emit_decl),  // IIR_ArchitectureDeclaration
  (v2c_generic_1_mtype) ((void (*)(pIIR_EntityDeclaration, int l))&m_emit_decl),  // IIR_EntityDeclaration
  (v2c_generic_1_mtype) ((void (*)(pIIR_ComponentDeclaration, int l))&m_emit_decl),  // IIR_ComponentDeclaration
  (v2c_generic_1_mtype) ((void (*)(pIIR_SubprogramDeclaration, int l))&m_emit_decl),  // IIR_SubprogramDeclaration
  (v2c_generic_1_mtype) ((void (*)(pIIR_SubprogramDeclaration, int l))&m_emit_decl),  // IIR_FunctionDeclaration
  (v2c_generic_1_mtype) ((void (*)(pIIR_SubprogramDeclaration, int l))&m_emit_decl),  // IIR_PredefinedFunctionDeclaration
  (v2c_generic_1_mtype) ((void (*)(pIIR_SubprogramDeclaration, int l))&m_emit_decl),  // IIR_ProcedureDeclaration
  (v2c_generic_1_mtype) ((void (*)(pIIR_SubprogramDeclaration, int l))&m_emit_decl),  // IIR_PredefinedProcedureDeclaration
  (v2c_generic_1_mtype) ((void (*)(pIIR_Declaration, int l))&m_emit_decl),  // IIR_LoopDeclarativeRegion
  0, // IIR_Type
  0, // IIR_FileType
  0, // IIR_AccessType
  0, // IIR_CompositeType
  0, // IIR_ArrayType
  0, // IIR_RecordType
  0, // IIR_ScalarType
  0, // IIR_PhysicalType
  0, // IIR_FloatingType
  0, // IIR_IntegerType
  0, // IIR_EnumerationType
  0, // IIR_Subtype
  0, // IIR_ArraySubtype
  0, // IIR_RecordSubtype
  0, // IIR_ScalarSubtype
  0, // IIR_Range
  0, // IIR_ArrayRange
  0, // IIR_Attr_ArrayREVERSE_RANGE
  0, // IIR_Attr_ArrayRANGE
  0, // IIR_ExplicitRange
  0, // IIR_List
  0, // IIR_IdentifierList
  0, // IIR_ConfigurationSpecificationList
  0, // IIR_ComponentInstantiationList
  0, // IIR_ElementAssociationList
  0, // IIR_IndexedAssociationList
  0, // IIR_ExpressionList
  0, // IIR_TypeList
  0, // IIR_WaveformList
  0, // IIR_UnitList
  0, // IIR_SequentialStatementList
  0, // IIR_LibraryUnitList
  0, // IIR_InterfaceList
  0, // IIR_EnumerationLiteralList
  0, // IIR_EntityClassEntryList
  0, // IIR_ElementDeclarationList
  0, // IIR_DeclarationList
  0, // IIR_ConfigurationItemList
  0, // IIR_ConcurrentStatementList
  0, // IIR_ChoiceList
  0, // IIR_CaseStatementAlternativeList
  0, // IIR_AttributeValueList
  0, // IIR_AssociationList
  0, // IIR_Tuple
  0, // IIR_ConfigurationSpecification
  0, // IIR_BindingIndication
  0, // IIR_AttributeValue
  0, // IIR_IndexedAssociation
  0, // IIR_OthersIndexedAssociation
  0, // IIR_RangeIndexedAssociation
  0, // IIR_SliceIndexedAssociation
  0, // IIR_SingleIndexedAssociation
  0, // IIR_ElementAssociation
  0, // IIR_WaveformElement
  0, // IIR_EntityClassEntry
  0, // IIR_Choice
  0, // IIR_ChoiceByOthers
  0, // IIR_ChoiceByRange
  0, // IIR_ChoiceByExpression
  0, // IIR_CaseStatementAlternative
  0, // IIR_AssociationElement
  0, // IIR_AssociationElementOpen
  0, // IIR_AssociationElementByExpression
  0, // IIR_Literal
  0, // IIR_AbstractLiteral
  0, // IIR_FloatingPointLiteral
  0, // IIR_IntegerLiteral
  0, // IIR_TextLiteral
  0, // IIR_StringLiteral
  0, // IIR_CharacterLiteral
  0, // IIR_Identifier
  0, // IIR_Dummy
  0, // IIR_Signature
  0, // IIR_PosInfo
  0, // IIR_PosInfo_Sheet
  0, // IIR_PosInfo_TextFile
};
static tree_chunk_tab ctab_1[1] = {
  { &fire_chunk_info, 205, mtab_1_fire },
};


static v2c_generic_2_mtype mtab_2_fire[] = {
  0, // IIR_Root
  (v2c_generic_2_mtype) ((void (*)(pIIR_SequentialStatement, int l))&m_emit_stat),  // IIR_SequentialStatement
  (v2c_generic_2_mtype) ((void (*)(pIIR_NullStatement, int l))&m_emit_stat),  // IIR_NullStatement
  (v2c_generic_2_mtype) ((void (*)(pIIR_ReturnStatement, int l))&m_emit_stat),  // IIR_ReturnStatement
  (v2c_generic_2_mtype) ((void (*)(pIIR_LoopControlStatement, int l))&m_emit_stat),  // IIR_LoopControlStatement
  (v2c_generic_2_mtype) ((void (*)(pIIR_LoopControlStatement, int l))&m_emit_stat),  // IIR_ExitStatement
  (v2c_generic_2_mtype) ((void (*)(pIIR_LoopControlStatement, int l))&m_emit_stat),  // IIR_NextStatement
  (v2c_generic_2_mtype) ((void (*)(pIIR_LoopStatement, int l))&m_emit_stat),  // IIR_LoopStatement
  (v2c_generic_2_mtype) ((void (*)(pIIR_LoopStatement, int l))&m_emit_stat),  // IIR_WhileLoopStatement
  (v2c_generic_2_mtype) ((void (*)(pIIR_LoopStatement, int l))&m_emit_stat),  // IIR_ForLoopStatement
  (v2c_generic_2_mtype) ((void (*)(pIIR_CaseStatement, int l))&m_emit_stat),  // IIR_CaseStatement
  (v2c_generic_2_mtype) ((void (*)(pIIR_IfStatement, int l))&m_emit_stat),  // IIR_IfStatement
  (v2c_generic_2_mtype) ((void (*)(pIIR_ProcedureCallStatement, int l))&m_emit_stat),  // IIR_ProcedureCallStatement
  (v2c_generic_2_mtype) ((void (*)(pIIR_VariableAssignmentStatement, int l))&m_emit_stat),  // IIR_VariableAssignmentStatement
  (v2c_generic_2_mtype) ((void (*)(pIIR_SignalAssignmentStatement, int l))&m_emit_stat),  // IIR_SignalAssignmentStatement
  (v2c_generic_2_mtype) ((void (*)(pIIR_ReportStatement, int l))&m_emit_stat),  // IIR_ReportStatement
  (v2c_generic_2_mtype) ((void (*)(pIIR_AssertionStatement, int l))&m_emit_stat),  // IIR_AssertionStatement
  (v2c_generic_2_mtype) ((void (*)(pIIR_WaitStatement, int l))&m_emit_stat),  // IIR_WaitStatement
  0, // IIR_Expression
  0, // IIR_ValueAttr
  0, // IIR_AttrTypeValue
  0, // IIR_Attr_LENGTH
  0, // IIR_Attr_ASCENDING
  0, // IIR_Attr_HIGH
  0, // IIR_Attr_LOW
  0, // IIR_Attr_RIGHT
  0, // IIR_Attr_LEFT
  0, // IIR_FunctionAttr
  0, // IIR_AttrArrayFunc
  0, // IIR_Attr_ArrayLENGTH
  0, // IIR_Attr_ArrayASCENDING
  0, // IIR_Attr_ArrayLOW
  0, // IIR_Attr_ArrayHIGH
  0, // IIR_Attr_ArrayRIGHT
  0, // IIR_Attr_ArrayLEFT
  0, // IIR_AttrTypeFunc
  0, // IIR_Attr_RIGHTOF
  0, // IIR_Attr_LEFTOF
  0, // IIR_Attr_PRED
  0, // IIR_Attr_SUCC
  0, // IIR_Attr_VAL
  0, // IIR_Attr_POS
  0, // IIR_Attr_VALUE
  0, // IIR_Attr_IMAGE
  0, // IIR_AttrSigFunc
  0, // IIR_Attr_DRIVING_VALUE
  0, // IIR_Attr_DRIVING
  0, // IIR_Attr_LAST_VALUE
  0, // IIR_Attr_LAST_ACTIVE
  0, // IIR_Attr_LAST_EVENT
  0, // IIR_Attr_ACTIVE
  0, // IIR_Attr_EVENT
  0, // IIR_ObjectReference
  0, // IIR_SignalAttr
  0, // IIR_Attr_TRANSACTION
  0, // IIR_Attr_QUIET
  0, // IIR_Attr_STABLE
  0, // IIR_Attr_DELAYED
  0, // IIR_GenericArrayReference
  0, // IIR_SliceReference
  0, // IIR_ArrayReference
  0, // IIR_RecordReference
  0, // IIR_AccessReference
  0, // IIR_SimpleReference
  0, // IIR_OpenExpression
  0, // IIR_Allocator
  0, // IIR_TypeConversion
  0, // IIR_QualifiedExpression
  0, // IIR_FunctionCall
  0, // IIR_Aggregate
  0, // IIR_ArrayAggregate
  0, // IIR_ArtificialArrayAggregate
  0, // IIR_RecordAggregate
  0, // IIR_ArtificialRecordAggregate
  0, // IIR_NullExpression
  0, // IIR_EnumLiteralReference
  0, // IIR_ArrayLiteralExpression
  0, // IIR_AbstractLiteralExpression
  0, // IIR_PhysicalLiteral
  0, // IIR_Declaration
  0, // IIR_UseClause
  0, // IIR_LibraryClause
  0, // IIR_Label
  0, // IIR_DisconnectSpecification
  0, // IIR_PhysicalUnit
  0, // IIR_LibraryDeclaration
  0, // IIR_AttributeDeclaration
  0, // IIR_ObjectDeclaration
  0, // IIR_InterfaceDeclaration
  0, // IIR_FileInterfaceDeclaration
  0, // IIR_SignalInterfaceDeclaration
  0, // IIR_VariableInterfaceDeclaration
  0, // IIR_ConstantInterfaceDeclaration
  0, // IIR_FileDeclaration
  0, // IIR_SignalDeclaration
  0, // IIR_VariableDeclaration
  0, // IIR_SharedVariableDeclaration
  0, // IIR_ConstantDeclaration
  0, // IIR_TypeDeclaration
  0, // IIR_SubtypeDeclaration
  0, // IIR_ElementDeclaration
  0, // IIR_EnumerationLiteral
  0, // IIR_DeclarativeRegion
  0, // IIR_ConcurrentStatement
  0, // IIR_ConcurrentGenerateStatement
  0, // IIR_ConcurrentGenerateIfStatement
  0, // IIR_ConcurrentGenerateForStatement
  0, // IIR_ComponentInstantiationStatement
  0, // IIR_ProcessStatement
  0, // IIR_SensitizedProcessStatement
  0, // IIR_ImplicitProcessStatement
  0, // IIR_BlockStatement
  0, // IIR_ConfigurationItem
  0, // IIR_ComponentConfiguration
  0, // IIR_BlockConfiguration
  0, // IIR_ArchitectureRef
  0, // IIR_LibraryUnit
  0, // IIR_ConfigurationDeclaration
  0, // IIR_PackageBodyDeclaration
  0, // IIR_PackageDeclaration
  0, // IIR_ArchitectureDeclaration
  0, // IIR_EntityDeclaration
  0, // IIR_ComponentDeclaration
  0, // IIR_SubprogramDeclaration
  0, // IIR_FunctionDeclaration
  0, // IIR_PredefinedFunctionDeclaration
  0, // IIR_ProcedureDeclaration
  0, // IIR_PredefinedProcedureDeclaration
  0, // IIR_LoopDeclarativeRegion
  0, // IIR_Type
  0, // IIR_FileType
  0, // IIR_AccessType
  0, // IIR_CompositeType
  0, // IIR_ArrayType
  0, // IIR_RecordType
  0, // IIR_ScalarType
  0, // IIR_PhysicalType
  0, // IIR_FloatingType
  0, // IIR_IntegerType
  0, // IIR_EnumerationType
  0, // IIR_Subtype
  0, // IIR_ArraySubtype
  0, // IIR_RecordSubtype
  0, // IIR_ScalarSubtype
  0, // IIR_Range
  0, // IIR_ArrayRange
  0, // IIR_Attr_ArrayREVERSE_RANGE
  0, // IIR_Attr_ArrayRANGE
  0, // IIR_ExplicitRange
  0, // IIR_List
  0, // IIR_IdentifierList
  0, // IIR_ConfigurationSpecificationList
  0, // IIR_ComponentInstantiationList
  0, // IIR_ElementAssociationList
  0, // IIR_IndexedAssociationList
  0, // IIR_ExpressionList
  0, // IIR_TypeList
  0, // IIR_WaveformList
  0, // IIR_UnitList
  0, // IIR_SequentialStatementList
  0, // IIR_LibraryUnitList
  0, // IIR_InterfaceList
  0, // IIR_EnumerationLiteralList
  0, // IIR_EntityClassEntryList
  0, // IIR_ElementDeclarationList
  0, // IIR_DeclarationList
  0, // IIR_ConfigurationItemList
  0, // IIR_ConcurrentStatementList
  0, // IIR_ChoiceList
  0, // IIR_CaseStatementAlternativeList
  0, // IIR_AttributeValueList
  0, // IIR_AssociationList
  0, // IIR_Tuple
  0, // IIR_ConfigurationSpecification
  0, // IIR_BindingIndication
  0, // IIR_AttributeValue
  0, // IIR_IndexedAssociation
  0, // IIR_OthersIndexedAssociation
  0, // IIR_RangeIndexedAssociation
  0, // IIR_SliceIndexedAssociation
  0, // IIR_SingleIndexedAssociation
  0, // IIR_ElementAssociation
  0, // IIR_WaveformElement
  0, // IIR_EntityClassEntry
  0, // IIR_Choice
  0, // IIR_ChoiceByOthers
  0, // IIR_ChoiceByRange
  0, // IIR_ChoiceByExpression
  0, // IIR_CaseStatementAlternative
  0, // IIR_AssociationElement
  0, // IIR_AssociationElementOpen
  0, // IIR_AssociationElementByExpression
  0, // IIR_Literal
  0, // IIR_AbstractLiteral
  0, // IIR_FloatingPointLiteral
  0, // IIR_IntegerLiteral
  0, // IIR_TextLiteral
  0, // IIR_StringLiteral
  0, // IIR_CharacterLiteral
  0, // IIR_Identifier
  0, // IIR_Dummy
  0, // IIR_Signature
  0, // IIR_PosInfo
  0, // IIR_PosInfo_Sheet
  0, // IIR_PosInfo_TextFile
};
static tree_chunk_tab ctab_2[1] = {
  { &fire_chunk_info, 205, mtab_2_fire },
};


static v2c_generic_3_mtype mtab_3_fire[] = {
  0, // IIR_Root
  0, // IIR_SequentialStatement
  0, // IIR_NullStatement
  0, // IIR_ReturnStatement
  0, // IIR_LoopControlStatement
  0, // IIR_ExitStatement
  0, // IIR_NextStatement
  0, // IIR_LoopStatement
  0, // IIR_WhileLoopStatement
  0, // IIR_ForLoopStatement
  0, // IIR_CaseStatement
  0, // IIR_IfStatement
  0, // IIR_ProcedureCallStatement
  0, // IIR_VariableAssignmentStatement
  0, // IIR_SignalAssignmentStatement
  0, // IIR_ReportStatement
  0, // IIR_AssertionStatement
  0, // IIR_WaitStatement
  (v2c_generic_3_mtype) ((void (*)(pIIR_Expression))&m_emit_expr),  // IIR_Expression
  (v2c_generic_3_mtype) ((void (*)(pIIR_Expression))&m_emit_expr),  // IIR_ValueAttr
  (v2c_generic_3_mtype) ((void (*)(pIIR_Expression))&m_emit_expr),  // IIR_AttrTypeValue
  (v2c_generic_3_mtype) ((void (*)(pIIR_Expression))&m_emit_expr),  // IIR_Attr_LENGTH
  (v2c_generic_3_mtype) ((void (*)(pIIR_Expression))&m_emit_expr),  // IIR_Attr_ASCENDING
  (v2c_generic_3_mtype) ((void (*)(pIIR_Expression))&m_emit_expr),  // IIR_Attr_HIGH
  (v2c_generic_3_mtype) ((void (*)(pIIR_Expression))&m_emit_expr),  // IIR_Attr_LOW
  (v2c_generic_3_mtype) ((void (*)(pIIR_Expression))&m_emit_expr),  // IIR_Attr_RIGHT
  (v2c_generic_3_mtype) ((void (*)(pIIR_Expression))&m_emit_expr),  // IIR_Attr_LEFT
  (v2c_generic_3_mtype) ((void (*)(pIIR_Expression))&m_emit_expr),  // IIR_FunctionAttr
  (v2c_generic_3_mtype) ((void (*)(pIIR_AttrArrayFunc))&m_emit_expr),  // IIR_AttrArrayFunc
  (v2c_generic_3_mtype) ((void (*)(pIIR_AttrArrayFunc))&m_emit_expr),  // IIR_Attr_ArrayLENGTH
  (v2c_generic_3_mtype) ((void (*)(pIIR_AttrArrayFunc))&m_emit_expr),  // IIR_Attr_ArrayASCENDING
  (v2c_generic_3_mtype) ((void (*)(pIIR_AttrArrayFunc))&m_emit_expr),  // IIR_Attr_ArrayLOW
  (v2c_generic_3_mtype) ((void (*)(pIIR_AttrArrayFunc))&m_emit_expr),  // IIR_Attr_ArrayHIGH
  (v2c_generic_3_mtype) ((void (*)(pIIR_AttrArrayFunc))&m_emit_expr),  // IIR_Attr_ArrayRIGHT
  (v2c_generic_3_mtype) ((void (*)(pIIR_AttrArrayFunc))&m_emit_expr),  // IIR_Attr_ArrayLEFT
  (v2c_generic_3_mtype) ((void (*)(pIIR_Expression))&m_emit_expr),  // IIR_AttrTypeFunc
  (v2c_generic_3_mtype) ((void (*)(pIIR_Expression))&m_emit_expr),  // IIR_Attr_RIGHTOF
  (v2c_generic_3_mtype) ((void (*)(pIIR_Expression))&m_emit_expr),  // IIR_Attr_LEFTOF
  (v2c_generic_3_mtype) ((void (*)(pIIR_Expression))&m_emit_expr),  // IIR_Attr_PRED
  (v2c_generic_3_mtype) ((void (*)(pIIR_Expression))&m_emit_expr),  // IIR_Attr_SUCC
  (v2c_generic_3_mtype) ((void (*)(pIIR_Expression))&m_emit_expr),  // IIR_Attr_VAL
  (v2c_generic_3_mtype) ((void (*)(pIIR_Expression))&m_emit_expr),  // IIR_Attr_POS
  (v2c_generic_3_mtype) ((void (*)(pIIR_Expression))&m_emit_expr),  // IIR_Attr_VALUE
  (v2c_generic_3_mtype) ((void (*)(pIIR_Expression))&m_emit_expr),  // IIR_Attr_IMAGE
  (v2c_generic_3_mtype) ((void (*)(pIIR_AttrSigFunc))&m_emit_expr),  // IIR_AttrSigFunc
  (v2c_generic_3_mtype) ((void (*)(pIIR_AttrSigFunc))&m_emit_expr),  // IIR_Attr_DRIVING_VALUE
  (v2c_generic_3_mtype) ((void (*)(pIIR_AttrSigFunc))&m_emit_expr),  // IIR_Attr_DRIVING
  (v2c_generic_3_mtype) ((void (*)(pIIR_AttrSigFunc))&m_emit_expr),  // IIR_Attr_LAST_VALUE
  (v2c_generic_3_mtype) ((void (*)(pIIR_AttrSigFunc))&m_emit_expr),  // IIR_Attr_LAST_ACTIVE
  (v2c_generic_3_mtype) ((void (*)(pIIR_AttrSigFunc))&m_emit_expr),  // IIR_Attr_LAST_EVENT
  (v2c_generic_3_mtype) ((void (*)(pIIR_AttrSigFunc))&m_emit_expr),  // IIR_Attr_ACTIVE
  (v2c_generic_3_mtype) ((void (*)(pIIR_AttrSigFunc))&m_emit_expr),  // IIR_Attr_EVENT
  (v2c_generic_3_mtype) ((void (*)(pIIR_Expression))&m_emit_expr),  // IIR_ObjectReference
  (v2c_generic_3_mtype) ((void (*)(pIIR_SignalAttr))&m_emit_expr),  // IIR_SignalAttr
  (v2c_generic_3_mtype) ((void (*)(pIIR_SignalAttr))&m_emit_expr),  // IIR_Attr_TRANSACTION
  (v2c_generic_3_mtype) ((void (*)(pIIR_SignalAttr))&m_emit_expr),  // IIR_Attr_QUIET
  (v2c_generic_3_mtype) ((void (*)(pIIR_SignalAttr))&m_emit_expr),  // IIR_Attr_STABLE
  (v2c_generic_3_mtype) ((void (*)(pIIR_SignalAttr))&m_emit_expr),  // IIR_Attr_DELAYED
  (v2c_generic_3_mtype) ((void (*)(pIIR_Expression))&m_emit_expr),  // IIR_GenericArrayReference
  (v2c_generic_3_mtype) ((void (*)(pIIR_SliceReference))&m_emit_expr),  // IIR_SliceReference
  (v2c_generic_3_mtype) ((void (*)(pIIR_ArrayReference))&m_emit_expr),  // IIR_ArrayReference
  (v2c_generic_3_mtype) ((void (*)(pIIR_RecordReference))&m_emit_expr),  // IIR_RecordReference
  (v2c_generic_3_mtype) ((void (*)(pIIR_AccessReference))&m_emit_expr),  // IIR_AccessReference
  (v2c_generic_3_mtype) ((void (*)(pIIR_SimpleReference))&m_emit_expr),  // IIR_SimpleReference
  (v2c_generic_3_mtype) ((void (*)(pIIR_Expression))&m_emit_expr),  // IIR_OpenExpression
  (v2c_generic_3_mtype) ((void (*)(pIIR_Expression))&m_emit_expr),  // IIR_Allocator
  (v2c_generic_3_mtype) ((void (*)(pIIR_TypeConversion))&m_emit_expr),  // IIR_TypeConversion
  (v2c_generic_3_mtype) ((void (*)(pIIR_QualifiedExpression))&m_emit_expr),  // IIR_QualifiedExpression
  (v2c_generic_3_mtype) ((void (*)(pIIR_FunctionCall))&m_emit_expr),  // IIR_FunctionCall
  (v2c_generic_3_mtype) ((void (*)(pIIR_Expression))&m_emit_expr),  // IIR_Aggregate
  (v2c_generic_3_mtype) ((void (*)(pIIR_ArrayAggregate))&m_emit_expr),  // IIR_ArrayAggregate
  (v2c_generic_3_mtype) ((void (*)(pIIR_ArrayAggregate))&m_emit_expr),  // IIR_ArtificialArrayAggregate
  (v2c_generic_3_mtype) ((void (*)(pIIR_RecordAggregate))&m_emit_expr),  // IIR_RecordAggregate
  (v2c_generic_3_mtype) ((void (*)(pIIR_RecordAggregate))&m_emit_expr),  // IIR_ArtificialRecordAggregate
  (v2c_generic_3_mtype) ((void (*)(pIIR_Expression))&m_emit_expr),  // IIR_NullExpression
  (v2c_generic_3_mtype) ((void (*)(pIIR_EnumLiteralReference))&m_emit_expr),  // IIR_EnumLiteralReference
  (v2c_generic_3_mtype) ((void (*)(pIIR_ArrayLiteralExpression))&m_emit_expr),  // IIR_ArrayLiteralExpression
  (v2c_generic_3_mtype) ((void (*)(pIIR_AbstractLiteralExpression))&m_emit_expr),  // IIR_AbstractLiteralExpression
  (v2c_generic_3_mtype) ((void (*)(pIIR_AbstractLiteralExpression))&m_emit_expr),  // IIR_PhysicalLiteral
  0, // IIR_Declaration
  0, // IIR_UseClause
  0, // IIR_LibraryClause
  0, // IIR_Label
  0, // IIR_DisconnectSpecification
  0, // IIR_PhysicalUnit
  0, // IIR_LibraryDeclaration
  0, // IIR_AttributeDeclaration
  0, // IIR_ObjectDeclaration
  0, // IIR_InterfaceDeclaration
  0, // IIR_FileInterfaceDeclaration
  0, // IIR_SignalInterfaceDeclaration
  0, // IIR_VariableInterfaceDeclaration
  0, // IIR_ConstantInterfaceDeclaration
  0, // IIR_FileDeclaration
  0, // IIR_SignalDeclaration
  0, // IIR_VariableDeclaration
  0, // IIR_SharedVariableDeclaration
  0, // IIR_ConstantDeclaration
  0, // IIR_TypeDeclaration
  0, // IIR_SubtypeDeclaration
  0, // IIR_ElementDeclaration
  0, // IIR_EnumerationLiteral
  0, // IIR_DeclarativeRegion
  0, // IIR_ConcurrentStatement
  0, // IIR_ConcurrentGenerateStatement
  0, // IIR_ConcurrentGenerateIfStatement
  0, // IIR_ConcurrentGenerateForStatement
  0, // IIR_ComponentInstantiationStatement
  0, // IIR_ProcessStatement
  0, // IIR_SensitizedProcessStatement
  0, // IIR_ImplicitProcessStatement
  0, // IIR_BlockStatement
  0, // IIR_ConfigurationItem
  0, // IIR_ComponentConfiguration
  0, // IIR_BlockConfiguration
  0, // IIR_ArchitectureRef
  0, // IIR_LibraryUnit
  0, // IIR_ConfigurationDeclaration
  0, // IIR_PackageBodyDeclaration
  0, // IIR_PackageDeclaration
  0, // IIR_ArchitectureDeclaration
  0, // IIR_EntityDeclaration
  0, // IIR_ComponentDeclaration
  0, // IIR_SubprogramDeclaration
  0, // IIR_FunctionDeclaration
  0, // IIR_PredefinedFunctionDeclaration
  0, // IIR_ProcedureDeclaration
  0, // IIR_PredefinedProcedureDeclaration
  0, // IIR_LoopDeclarativeRegion
  0, // IIR_Type
  0, // IIR_FileType
  0, // IIR_AccessType
  0, // IIR_CompositeType
  0, // IIR_ArrayType
  0, // IIR_RecordType
  0, // IIR_ScalarType
  0, // IIR_PhysicalType
  0, // IIR_FloatingType
  0, // IIR_IntegerType
  0, // IIR_EnumerationType
  0, // IIR_Subtype
  0, // IIR_ArraySubtype
  0, // IIR_RecordSubtype
  0, // IIR_ScalarSubtype
  0, // IIR_Range
  0, // IIR_ArrayRange
  0, // IIR_Attr_ArrayREVERSE_RANGE
  0, // IIR_Attr_ArrayRANGE
  0, // IIR_ExplicitRange
  0, // IIR_List
  0, // IIR_IdentifierList
  0, // IIR_ConfigurationSpecificationList
  0, // IIR_ComponentInstantiationList
  0, // IIR_ElementAssociationList
  0, // IIR_IndexedAssociationList
  0, // IIR_ExpressionList
  0, // IIR_TypeList
  0, // IIR_WaveformList
  0, // IIR_UnitList
  0, // IIR_SequentialStatementList
  0, // IIR_LibraryUnitList
  0, // IIR_InterfaceList
  0, // IIR_EnumerationLiteralList
  0, // IIR_EntityClassEntryList
  0, // IIR_ElementDeclarationList
  0, // IIR_DeclarationList
  0, // IIR_ConfigurationItemList
  0, // IIR_ConcurrentStatementList
  0, // IIR_ChoiceList
  0, // IIR_CaseStatementAlternativeList
  0, // IIR_AttributeValueList
  0, // IIR_AssociationList
  0, // IIR_Tuple
  0, // IIR_ConfigurationSpecification
  0, // IIR_BindingIndication
  0, // IIR_AttributeValue
  0, // IIR_IndexedAssociation
  0, // IIR_OthersIndexedAssociation
  0, // IIR_RangeIndexedAssociation
  0, // IIR_SliceIndexedAssociation
  0, // IIR_SingleIndexedAssociation
  0, // IIR_ElementAssociation
  0, // IIR_WaveformElement
  0, // IIR_EntityClassEntry
  0, // IIR_Choice
  0, // IIR_ChoiceByOthers
  0, // IIR_ChoiceByRange
  0, // IIR_ChoiceByExpression
  0, // IIR_CaseStatementAlternative
  0, // IIR_AssociationElement
  0, // IIR_AssociationElementOpen
  0, // IIR_AssociationElementByExpression
  0, // IIR_Literal
  0, // IIR_AbstractLiteral
  0, // IIR_FloatingPointLiteral
  0, // IIR_IntegerLiteral
  0, // IIR_TextLiteral
  0, // IIR_StringLiteral
  0, // IIR_CharacterLiteral
  0, // IIR_Identifier
  0, // IIR_Dummy
  0, // IIR_Signature
  0, // IIR_PosInfo
  0, // IIR_PosInfo_Sheet
  0, // IIR_PosInfo_TextFile
};
static tree_chunk_tab ctab_3[1] = {
  { &fire_chunk_info, 205, mtab_3_fire },
};


static v2c_generic_4_mtype mtab_4_fire[] = {
  0, // IIR_Root
  0, // IIR_SequentialStatement
  0, // IIR_NullStatement
  0, // IIR_ReturnStatement
  0, // IIR_LoopControlStatement
  0, // IIR_ExitStatement
  0, // IIR_NextStatement
  0, // IIR_LoopStatement
  0, // IIR_WhileLoopStatement
  0, // IIR_ForLoopStatement
  0, // IIR_CaseStatement
  0, // IIR_IfStatement
  0, // IIR_ProcedureCallStatement
  0, // IIR_VariableAssignmentStatement
  0, // IIR_SignalAssignmentStatement
  0, // IIR_ReportStatement
  0, // IIR_AssertionStatement
  0, // IIR_WaitStatement
  0, // IIR_Expression
  0, // IIR_ValueAttr
  0, // IIR_AttrTypeValue
  0, // IIR_Attr_LENGTH
  0, // IIR_Attr_ASCENDING
  0, // IIR_Attr_HIGH
  0, // IIR_Attr_LOW
  0, // IIR_Attr_RIGHT
  0, // IIR_Attr_LEFT
  0, // IIR_FunctionAttr
  0, // IIR_AttrArrayFunc
  0, // IIR_Attr_ArrayLENGTH
  0, // IIR_Attr_ArrayASCENDING
  0, // IIR_Attr_ArrayLOW
  0, // IIR_Attr_ArrayHIGH
  0, // IIR_Attr_ArrayRIGHT
  0, // IIR_Attr_ArrayLEFT
  0, // IIR_AttrTypeFunc
  0, // IIR_Attr_RIGHTOF
  0, // IIR_Attr_LEFTOF
  0, // IIR_Attr_PRED
  0, // IIR_Attr_SUCC
  0, // IIR_Attr_VAL
  0, // IIR_Attr_POS
  0, // IIR_Attr_VALUE
  0, // IIR_Attr_IMAGE
  0, // IIR_AttrSigFunc
  0, // IIR_Attr_DRIVING_VALUE
  0, // IIR_Attr_DRIVING
  0, // IIR_Attr_LAST_VALUE
  0, // IIR_Attr_LAST_ACTIVE
  0, // IIR_Attr_LAST_EVENT
  0, // IIR_Attr_ACTIVE
  0, // IIR_Attr_EVENT
  0, // IIR_ObjectReference
  0, // IIR_SignalAttr
  0, // IIR_Attr_TRANSACTION
  0, // IIR_Attr_QUIET
  0, // IIR_Attr_STABLE
  0, // IIR_Attr_DELAYED
  0, // IIR_GenericArrayReference
  0, // IIR_SliceReference
  0, // IIR_ArrayReference
  0, // IIR_RecordReference
  0, // IIR_AccessReference
  0, // IIR_SimpleReference
  0, // IIR_OpenExpression
  0, // IIR_Allocator
  0, // IIR_TypeConversion
  0, // IIR_QualifiedExpression
  0, // IIR_FunctionCall
  0, // IIR_Aggregate
  0, // IIR_ArrayAggregate
  0, // IIR_ArtificialArrayAggregate
  0, // IIR_RecordAggregate
  0, // IIR_ArtificialRecordAggregate
  0, // IIR_NullExpression
  0, // IIR_EnumLiteralReference
  0, // IIR_ArrayLiteralExpression
  0, // IIR_AbstractLiteralExpression
  0, // IIR_PhysicalLiteral
  0, // IIR_Declaration
  0, // IIR_UseClause
  0, // IIR_LibraryClause
  0, // IIR_Label
  0, // IIR_DisconnectSpecification
  0, // IIR_PhysicalUnit
  0, // IIR_LibraryDeclaration
  0, // IIR_AttributeDeclaration
  0, // IIR_ObjectDeclaration
  0, // IIR_InterfaceDeclaration
  0, // IIR_FileInterfaceDeclaration
  0, // IIR_SignalInterfaceDeclaration
  0, // IIR_VariableInterfaceDeclaration
  0, // IIR_ConstantInterfaceDeclaration
  0, // IIR_FileDeclaration
  0, // IIR_SignalDeclaration
  0, // IIR_VariableDeclaration
  0, // IIR_SharedVariableDeclaration
  0, // IIR_ConstantDeclaration
  0, // IIR_TypeDeclaration
  0, // IIR_SubtypeDeclaration
  0, // IIR_ElementDeclaration
  0, // IIR_EnumerationLiteral
  0, // IIR_DeclarativeRegion
  (v2c_generic_4_mtype) ((void (*)(pIIR_ConcurrentStatement, int l))&m_emit_conc_stat),  // IIR_ConcurrentStatement
  (v2c_generic_4_mtype) ((void (*)(pIIR_ConcurrentGenerateStatement, int l))&m_emit_conc_stat),  // IIR_ConcurrentGenerateStatement
  (v2c_generic_4_mtype) ((void (*)(pIIR_ConcurrentGenerateStatement, int l))&m_emit_conc_stat),  // IIR_ConcurrentGenerateIfStatement
  (v2c_generic_4_mtype) ((void (*)(pIIR_ConcurrentGenerateStatement, int l))&m_emit_conc_stat),  // IIR_ConcurrentGenerateForStatement
  (v2c_generic_4_mtype) ((void (*)(pIIR_ComponentInstantiationStatement, int l))&m_emit_conc_stat),  // IIR_ComponentInstantiationStatement
  (v2c_generic_4_mtype) ((void (*)(pIIR_ProcessStatement, int l))&m_emit_conc_stat),  // IIR_ProcessStatement
  (v2c_generic_4_mtype) ((void (*)(pIIR_ProcessStatement, int l))&m_emit_conc_stat),  // IIR_SensitizedProcessStatement
  (v2c_generic_4_mtype) ((void (*)(pIIR_ProcessStatement, int l))&m_emit_conc_stat),  // IIR_ImplicitProcessStatement
  (v2c_generic_4_mtype) ((void (*)(pIIR_BlockStatement, int l))&m_emit_conc_stat),  // IIR_BlockStatement
  0, // IIR_ConfigurationItem
  0, // IIR_ComponentConfiguration
  0, // IIR_BlockConfiguration
  0, // IIR_ArchitectureRef
  0, // IIR_LibraryUnit
  0, // IIR_ConfigurationDeclaration
  0, // IIR_PackageBodyDeclaration
  0, // IIR_PackageDeclaration
  0, // IIR_ArchitectureDeclaration
  0, // IIR_EntityDeclaration
  0, // IIR_ComponentDeclaration
  0, // IIR_SubprogramDeclaration
  0, // IIR_FunctionDeclaration
  0, // IIR_PredefinedFunctionDeclaration
  0, // IIR_ProcedureDeclaration
  0, // IIR_PredefinedProcedureDeclaration
  0, // IIR_LoopDeclarativeRegion
  0, // IIR_Type
  0, // IIR_FileType
  0, // IIR_AccessType
  0, // IIR_CompositeType
  0, // IIR_ArrayType
  0, // IIR_RecordType
  0, // IIR_ScalarType
  0, // IIR_PhysicalType
  0, // IIR_FloatingType
  0, // IIR_IntegerType
  0, // IIR_EnumerationType
  0, // IIR_Subtype
  0, // IIR_ArraySubtype
  0, // IIR_RecordSubtype
  0, // IIR_ScalarSubtype
  0, // IIR_Range
  0, // IIR_ArrayRange
  0, // IIR_Attr_ArrayREVERSE_RANGE
  0, // IIR_Attr_ArrayRANGE
  0, // IIR_ExplicitRange
  0, // IIR_List
  0, // IIR_IdentifierList
  0, // IIR_ConfigurationSpecificationList
  0, // IIR_ComponentInstantiationList
  0, // IIR_ElementAssociationList
  0, // IIR_IndexedAssociationList
  0, // IIR_ExpressionList
  0, // IIR_TypeList
  0, // IIR_WaveformList
  0, // IIR_UnitList
  0, // IIR_SequentialStatementList
  0, // IIR_LibraryUnitList
  0, // IIR_InterfaceList
  0, // IIR_EnumerationLiteralList
  0, // IIR_EntityClassEntryList
  0, // IIR_ElementDeclarationList
  0, // IIR_DeclarationList
  0, // IIR_ConfigurationItemList
  0, // IIR_ConcurrentStatementList
  0, // IIR_ChoiceList
  0, // IIR_CaseStatementAlternativeList
  0, // IIR_AttributeValueList
  0, // IIR_AssociationList
  0, // IIR_Tuple
  0, // IIR_ConfigurationSpecification
  0, // IIR_BindingIndication
  0, // IIR_AttributeValue
  0, // IIR_IndexedAssociation
  0, // IIR_OthersIndexedAssociation
  0, // IIR_RangeIndexedAssociation
  0, // IIR_SliceIndexedAssociation
  0, // IIR_SingleIndexedAssociation
  0, // IIR_ElementAssociation
  0, // IIR_WaveformElement
  0, // IIR_EntityClassEntry
  0, // IIR_Choice
  0, // IIR_ChoiceByOthers
  0, // IIR_ChoiceByRange
  0, // IIR_ChoiceByExpression
  0, // IIR_CaseStatementAlternative
  0, // IIR_AssociationElement
  0, // IIR_AssociationElementOpen
  0, // IIR_AssociationElementByExpression
  0, // IIR_Literal
  0, // IIR_AbstractLiteral
  0, // IIR_FloatingPointLiteral
  0, // IIR_IntegerLiteral
  0, // IIR_TextLiteral
  0, // IIR_StringLiteral
  0, // IIR_CharacterLiteral
  0, // IIR_Identifier
  0, // IIR_Dummy
  0, // IIR_Signature
  0, // IIR_PosInfo
  0, // IIR_PosInfo_Sheet
  0, // IIR_PosInfo_TextFile
};
static tree_chunk_tab ctab_4[1] = {
  { &fire_chunk_info, 205, mtab_4_fire },
};


static v2c_generic_5_mtype mtab_5_fire[] = {
  0, // IIR_Root
  0, // IIR_SequentialStatement
  0, // IIR_NullStatement
  0, // IIR_ReturnStatement
  0, // IIR_LoopControlStatement
  0, // IIR_ExitStatement
  0, // IIR_NextStatement
  0, // IIR_LoopStatement
  0, // IIR_WhileLoopStatement
  0, // IIR_ForLoopStatement
  0, // IIR_CaseStatement
  0, // IIR_IfStatement
  0, // IIR_ProcedureCallStatement
  0, // IIR_VariableAssignmentStatement
  0, // IIR_SignalAssignmentStatement
  0, // IIR_ReportStatement
  0, // IIR_AssertionStatement
  0, // IIR_WaitStatement
  0, // IIR_Expression
  0, // IIR_ValueAttr
  0, // IIR_AttrTypeValue
  0, // IIR_Attr_LENGTH
  0, // IIR_Attr_ASCENDING
  0, // IIR_Attr_HIGH
  0, // IIR_Attr_LOW
  0, // IIR_Attr_RIGHT
  0, // IIR_Attr_LEFT
  0, // IIR_FunctionAttr
  0, // IIR_AttrArrayFunc
  0, // IIR_Attr_ArrayLENGTH
  0, // IIR_Attr_ArrayASCENDING
  0, // IIR_Attr_ArrayLOW
  0, // IIR_Attr_ArrayHIGH
  0, // IIR_Attr_ArrayRIGHT
  0, // IIR_Attr_ArrayLEFT
  0, // IIR_AttrTypeFunc
  0, // IIR_Attr_RIGHTOF
  0, // IIR_Attr_LEFTOF
  0, // IIR_Attr_PRED
  0, // IIR_Attr_SUCC
  0, // IIR_Attr_VAL
  0, // IIR_Attr_POS
  0, // IIR_Attr_VALUE
  0, // IIR_Attr_IMAGE
  0, // IIR_AttrSigFunc
  0, // IIR_Attr_DRIVING_VALUE
  0, // IIR_Attr_DRIVING
  0, // IIR_Attr_LAST_VALUE
  0, // IIR_Attr_LAST_ACTIVE
  0, // IIR_Attr_LAST_EVENT
  0, // IIR_Attr_ACTIVE
  0, // IIR_Attr_EVENT
  0, // IIR_ObjectReference
  0, // IIR_SignalAttr
  0, // IIR_Attr_TRANSACTION
  0, // IIR_Attr_QUIET
  0, // IIR_Attr_STABLE
  0, // IIR_Attr_DELAYED
  0, // IIR_GenericArrayReference
  0, // IIR_SliceReference
  0, // IIR_ArrayReference
  0, // IIR_RecordReference
  0, // IIR_AccessReference
  0, // IIR_SimpleReference
  0, // IIR_OpenExpression
  0, // IIR_Allocator
  0, // IIR_TypeConversion
  0, // IIR_QualifiedExpression
  0, // IIR_FunctionCall
  0, // IIR_Aggregate
  0, // IIR_ArrayAggregate
  0, // IIR_ArtificialArrayAggregate
  0, // IIR_RecordAggregate
  0, // IIR_ArtificialRecordAggregate
  0, // IIR_NullExpression
  0, // IIR_EnumLiteralReference
  0, // IIR_ArrayLiteralExpression
  0, // IIR_AbstractLiteralExpression
  0, // IIR_PhysicalLiteral
  0, // IIR_Declaration
  0, // IIR_UseClause
  0, // IIR_LibraryClause
  0, // IIR_Label
  0, // IIR_DisconnectSpecification
  0, // IIR_PhysicalUnit
  0, // IIR_LibraryDeclaration
  0, // IIR_AttributeDeclaration
  0, // IIR_ObjectDeclaration
  0, // IIR_InterfaceDeclaration
  0, // IIR_FileInterfaceDeclaration
  0, // IIR_SignalInterfaceDeclaration
  0, // IIR_VariableInterfaceDeclaration
  0, // IIR_ConstantInterfaceDeclaration
  0, // IIR_FileDeclaration
  0, // IIR_SignalDeclaration
  0, // IIR_VariableDeclaration
  0, // IIR_SharedVariableDeclaration
  0, // IIR_ConstantDeclaration
  0, // IIR_TypeDeclaration
  0, // IIR_SubtypeDeclaration
  0, // IIR_ElementDeclaration
  0, // IIR_EnumerationLiteral
  0, // IIR_DeclarativeRegion
  0, // IIR_ConcurrentStatement
  0, // IIR_ConcurrentGenerateStatement
  0, // IIR_ConcurrentGenerateIfStatement
  0, // IIR_ConcurrentGenerateForStatement
  0, // IIR_ComponentInstantiationStatement
  0, // IIR_ProcessStatement
  0, // IIR_SensitizedProcessStatement
  0, // IIR_ImplicitProcessStatement
  (v2c_generic_5_mtype) ((void (*)(pIIR_BlockStatement, int l))&m_emit_start_of_context),  // IIR_BlockStatement
  0, // IIR_ConfigurationItem
  0, // IIR_ComponentConfiguration
  0, // IIR_BlockConfiguration
  0, // IIR_ArchitectureRef
  0, // IIR_LibraryUnit
  0, // IIR_ConfigurationDeclaration
  0, // IIR_PackageBodyDeclaration
  0, // IIR_PackageDeclaration
  (v2c_generic_5_mtype) ((void (*)(pIIR_ArchitectureDeclaration, int l))&m_emit_start_of_context),  // IIR_ArchitectureDeclaration
  0, // IIR_EntityDeclaration
  0, // IIR_ComponentDeclaration
  0, // IIR_SubprogramDeclaration
  0, // IIR_FunctionDeclaration
  0, // IIR_PredefinedFunctionDeclaration
  0, // IIR_ProcedureDeclaration
  0, // IIR_PredefinedProcedureDeclaration
  0, // IIR_LoopDeclarativeRegion
  0, // IIR_Type
  0, // IIR_FileType
  0, // IIR_AccessType
  0, // IIR_CompositeType
  0, // IIR_ArrayType
  0, // IIR_RecordType
  0, // IIR_ScalarType
  0, // IIR_PhysicalType
  0, // IIR_FloatingType
  0, // IIR_IntegerType
  0, // IIR_EnumerationType
  0, // IIR_Subtype
  0, // IIR_ArraySubtype
  0, // IIR_RecordSubtype
  0, // IIR_ScalarSubtype
  0, // IIR_Range
  0, // IIR_ArrayRange
  0, // IIR_Attr_ArrayREVERSE_RANGE
  0, // IIR_Attr_ArrayRANGE
  0, // IIR_ExplicitRange
  0, // IIR_List
  0, // IIR_IdentifierList
  0, // IIR_ConfigurationSpecificationList
  0, // IIR_ComponentInstantiationList
  0, // IIR_ElementAssociationList
  0, // IIR_IndexedAssociationList
  0, // IIR_ExpressionList
  0, // IIR_TypeList
  0, // IIR_WaveformList
  0, // IIR_UnitList
  0, // IIR_SequentialStatementList
  0, // IIR_LibraryUnitList
  0, // IIR_InterfaceList
  0, // IIR_EnumerationLiteralList
  0, // IIR_EntityClassEntryList
  0, // IIR_ElementDeclarationList
  0, // IIR_DeclarationList
  0, // IIR_ConfigurationItemList
  0, // IIR_ConcurrentStatementList
  0, // IIR_ChoiceList
  0, // IIR_CaseStatementAlternativeList
  0, // IIR_AttributeValueList
  0, // IIR_AssociationList
  0, // IIR_Tuple
  0, // IIR_ConfigurationSpecification
  0, // IIR_BindingIndication
  0, // IIR_AttributeValue
  0, // IIR_IndexedAssociation
  0, // IIR_OthersIndexedAssociation
  0, // IIR_RangeIndexedAssociation
  0, // IIR_SliceIndexedAssociation
  0, // IIR_SingleIndexedAssociation
  0, // IIR_ElementAssociation
  0, // IIR_WaveformElement
  0, // IIR_EntityClassEntry
  0, // IIR_Choice
  0, // IIR_ChoiceByOthers
  0, // IIR_ChoiceByRange
  0, // IIR_ChoiceByExpression
  0, // IIR_CaseStatementAlternative
  0, // IIR_AssociationElement
  0, // IIR_AssociationElementOpen
  0, // IIR_AssociationElementByExpression
  0, // IIR_Literal
  0, // IIR_AbstractLiteral
  0, // IIR_FloatingPointLiteral
  0, // IIR_IntegerLiteral
  0, // IIR_TextLiteral
  0, // IIR_StringLiteral
  0, // IIR_CharacterLiteral
  0, // IIR_Identifier
  0, // IIR_Dummy
  0, // IIR_Signature
  0, // IIR_PosInfo
  0, // IIR_PosInfo_Sheet
  0, // IIR_PosInfo_TextFile
};
static tree_chunk_tab ctab_5[1] = {
  { &fire_chunk_info, 205, mtab_5_fire },
};


static v2c_generic_6_mtype mtab_6_fire[] = {
  0, // IIR_Root
  0, // IIR_SequentialStatement
  0, // IIR_NullStatement
  0, // IIR_ReturnStatement
  0, // IIR_LoopControlStatement
  0, // IIR_ExitStatement
  0, // IIR_NextStatement
  0, // IIR_LoopStatement
  0, // IIR_WhileLoopStatement
  0, // IIR_ForLoopStatement
  0, // IIR_CaseStatement
  0, // IIR_IfStatement
  0, // IIR_ProcedureCallStatement
  0, // IIR_VariableAssignmentStatement
  0, // IIR_SignalAssignmentStatement
  0, // IIR_ReportStatement
  0, // IIR_AssertionStatement
  0, // IIR_WaitStatement
  0, // IIR_Expression
  0, // IIR_ValueAttr
  0, // IIR_AttrTypeValue
  0, // IIR_Attr_LENGTH
  0, // IIR_Attr_ASCENDING
  0, // IIR_Attr_HIGH
  0, // IIR_Attr_LOW
  0, // IIR_Attr_RIGHT
  0, // IIR_Attr_LEFT
  0, // IIR_FunctionAttr
  0, // IIR_AttrArrayFunc
  0, // IIR_Attr_ArrayLENGTH
  0, // IIR_Attr_ArrayASCENDING
  0, // IIR_Attr_ArrayLOW
  0, // IIR_Attr_ArrayHIGH
  0, // IIR_Attr_ArrayRIGHT
  0, // IIR_Attr_ArrayLEFT
  0, // IIR_AttrTypeFunc
  0, // IIR_Attr_RIGHTOF
  0, // IIR_Attr_LEFTOF
  0, // IIR_Attr_PRED
  0, // IIR_Attr_SUCC
  0, // IIR_Attr_VAL
  0, // IIR_Attr_POS
  0, // IIR_Attr_VALUE
  0, // IIR_Attr_IMAGE
  0, // IIR_AttrSigFunc
  0, // IIR_Attr_DRIVING_VALUE
  0, // IIR_Attr_DRIVING
  0, // IIR_Attr_LAST_VALUE
  0, // IIR_Attr_LAST_ACTIVE
  0, // IIR_Attr_LAST_EVENT
  0, // IIR_Attr_ACTIVE
  0, // IIR_Attr_EVENT
  0, // IIR_ObjectReference
  0, // IIR_SignalAttr
  0, // IIR_Attr_TRANSACTION
  0, // IIR_Attr_QUIET
  0, // IIR_Attr_STABLE
  0, // IIR_Attr_DELAYED
  0, // IIR_GenericArrayReference
  0, // IIR_SliceReference
  0, // IIR_ArrayReference
  0, // IIR_RecordReference
  0, // IIR_AccessReference
  0, // IIR_SimpleReference
  0, // IIR_OpenExpression
  0, // IIR_Allocator
  0, // IIR_TypeConversion
  0, // IIR_QualifiedExpression
  0, // IIR_FunctionCall
  0, // IIR_Aggregate
  0, // IIR_ArrayAggregate
  0, // IIR_ArtificialArrayAggregate
  0, // IIR_RecordAggregate
  0, // IIR_ArtificialRecordAggregate
  0, // IIR_NullExpression
  0, // IIR_EnumLiteralReference
  0, // IIR_ArrayLiteralExpression
  0, // IIR_AbstractLiteralExpression
  0, // IIR_PhysicalLiteral
  0, // IIR_Declaration
  0, // IIR_UseClause
  0, // IIR_LibraryClause
  0, // IIR_Label
  0, // IIR_DisconnectSpecification
  0, // IIR_PhysicalUnit
  0, // IIR_LibraryDeclaration
  0, // IIR_AttributeDeclaration
  0, // IIR_ObjectDeclaration
  0, // IIR_InterfaceDeclaration
  0, // IIR_FileInterfaceDeclaration
  0, // IIR_SignalInterfaceDeclaration
  0, // IIR_VariableInterfaceDeclaration
  0, // IIR_ConstantInterfaceDeclaration
  0, // IIR_FileDeclaration
  0, // IIR_SignalDeclaration
  0, // IIR_VariableDeclaration
  0, // IIR_SharedVariableDeclaration
  0, // IIR_ConstantDeclaration
  0, // IIR_TypeDeclaration
  0, // IIR_SubtypeDeclaration
  0, // IIR_ElementDeclaration
  0, // IIR_EnumerationLiteral
  0, // IIR_DeclarativeRegion
  0, // IIR_ConcurrentStatement
  0, // IIR_ConcurrentGenerateStatement
  0, // IIR_ConcurrentGenerateIfStatement
  0, // IIR_ConcurrentGenerateForStatement
  0, // IIR_ComponentInstantiationStatement
  0, // IIR_ProcessStatement
  0, // IIR_SensitizedProcessStatement
  0, // IIR_ImplicitProcessStatement
  (v2c_generic_6_mtype) ((void (*)(pIIR_BlockStatement, int l))&m_emit_end_of_context),  // IIR_BlockStatement
  0, // IIR_ConfigurationItem
  0, // IIR_ComponentConfiguration
  0, // IIR_BlockConfiguration
  0, // IIR_ArchitectureRef
  0, // IIR_LibraryUnit
  0, // IIR_ConfigurationDeclaration
  0, // IIR_PackageBodyDeclaration
  0, // IIR_PackageDeclaration
  (v2c_generic_6_mtype) ((void (*)(pIIR_ArchitectureDeclaration, int l))&m_emit_end_of_context),  // IIR_ArchitectureDeclaration
  0, // IIR_EntityDeclaration
  0, // IIR_ComponentDeclaration
  0, // IIR_SubprogramDeclaration
  0, // IIR_FunctionDeclaration
  0, // IIR_PredefinedFunctionDeclaration
  0, // IIR_ProcedureDeclaration
  0, // IIR_PredefinedProcedureDeclaration
  0, // IIR_LoopDeclarativeRegion
  0, // IIR_Type
  0, // IIR_FileType
  0, // IIR_AccessType
  0, // IIR_CompositeType
  0, // IIR_ArrayType
  0, // IIR_RecordType
  0, // IIR_ScalarType
  0, // IIR_PhysicalType
  0, // IIR_FloatingType
  0, // IIR_IntegerType
  0, // IIR_EnumerationType
  0, // IIR_Subtype
  0, // IIR_ArraySubtype
  0, // IIR_RecordSubtype
  0, // IIR_ScalarSubtype
  0, // IIR_Range
  0, // IIR_ArrayRange
  0, // IIR_Attr_ArrayREVERSE_RANGE
  0, // IIR_Attr_ArrayRANGE
  0, // IIR_ExplicitRange
  0, // IIR_List
  0, // IIR_IdentifierList
  0, // IIR_ConfigurationSpecificationList
  0, // IIR_ComponentInstantiationList
  0, // IIR_ElementAssociationList
  0, // IIR_IndexedAssociationList
  0, // IIR_ExpressionList
  0, // IIR_TypeList
  0, // IIR_WaveformList
  0, // IIR_UnitList
  0, // IIR_SequentialStatementList
  0, // IIR_LibraryUnitList
  0, // IIR_InterfaceList
  0, // IIR_EnumerationLiteralList
  0, // IIR_EntityClassEntryList
  0, // IIR_ElementDeclarationList
  0, // IIR_DeclarationList
  0, // IIR_ConfigurationItemList
  0, // IIR_ConcurrentStatementList
  0, // IIR_ChoiceList
  0, // IIR_CaseStatementAlternativeList
  0, // IIR_AttributeValueList
  0, // IIR_AssociationList
  0, // IIR_Tuple
  0, // IIR_ConfigurationSpecification
  0, // IIR_BindingIndication
  0, // IIR_AttributeValue
  0, // IIR_IndexedAssociation
  0, // IIR_OthersIndexedAssociation
  0, // IIR_RangeIndexedAssociation
  0, // IIR_SliceIndexedAssociation
  0, // IIR_SingleIndexedAssociation
  0, // IIR_ElementAssociation
  0, // IIR_WaveformElement
  0, // IIR_EntityClassEntry
  0, // IIR_Choice
  0, // IIR_ChoiceByOthers
  0, // IIR_ChoiceByRange
  0, // IIR_ChoiceByExpression
  0, // IIR_CaseStatementAlternative
  0, // IIR_AssociationElement
  0, // IIR_AssociationElementOpen
  0, // IIR_AssociationElementByExpression
  0, // IIR_Literal
  0, // IIR_AbstractLiteral
  0, // IIR_FloatingPointLiteral
  0, // IIR_IntegerLiteral
  0, // IIR_TextLiteral
  0, // IIR_StringLiteral
  0, // IIR_CharacterLiteral
  0, // IIR_Identifier
  0, // IIR_Dummy
  0, // IIR_Signature
  0, // IIR_PosInfo
  0, // IIR_PosInfo_Sheet
  0, // IIR_PosInfo_TextFile
};
static tree_chunk_tab ctab_6[1] = {
  { &fire_chunk_info, 205, mtab_6_fire },
};


static tree_kind v2c_kinds[] = {
};

struct tree_chunk_info v2c_chunk_info = {
  -1,
  "v2c",
  0,
  v2c_kinds
};

void init_v2c_chunk ()
{
  if (v2c_chunk_info.chunk_id != -1)
    return;
  init_fire_chunk ();

  tree_register_chunk (&v2c_chunk_info);
  v2c_generic_0.init ("emit_def");
  v2c_generic_1.init ("emit_decl");
  v2c_generic_2.init ("emit_stat");
  v2c_generic_3.init ("emit_expr");
  v2c_generic_4.init ("emit_conc_stat");
  v2c_generic_5.init ("emit_start_of_context");
  v2c_generic_6.init ("emit_end_of_context");
  v2c_generic_0.merge (1, ctab_0);
  v2c_generic_1.merge (1, ctab_1);
  v2c_generic_2.merge (1, ctab_2);
  v2c_generic_3.merge (1, ctab_3);
  v2c_generic_4.merge (1, ctab_4);
  v2c_generic_5.merge (1, ctab_5);
  v2c_generic_6.merge (1, ctab_6);
}

struct v2c_auto_initializer {
  v2c_auto_initializer () { init_v2c_chunk (); }
} v2c_ignition;
